import fs from 'fs';
import path from 'path';

// Read current stockDictionary.ts
const targetPath = 'd:/APP/股票紀錄/src/data/stockDictionary.ts';
const content = fs.readFileSync(targetPath, 'utf8');

// Let's create an expanded list of 550+ US stocks
const additionalUS = [
  // S&P 500 & Nasdaq 100 comprehensive additions
  { symbol: 'AAL', name: '美國航空', englishName: 'American Airlines Group Inc.', category: '航空運輸' },
  { symbol: 'DAL', name: '達美航空', englishName: 'Delta Air Lines Inc.', category: '航空運輸' },
  { symbol: 'LUV', name: '西南航空', englishName: 'Southwest Airlines Co.', category: '航空運輸' },
  { symbol: 'UAL', name: '聯合航空', englishName: 'United Airlines Holdings Inc.', category: '航空運輸' },
  { symbol: 'AES', name: '愛爾斯能源', englishName: 'The AES Corporation', category: '電力公用' },
  { symbol: 'AKAM', name: '阿卡邁科技 (Akamai)', englishName: 'Akamai Technologies Inc.', category: 'CDN雲端' },
  { symbol: 'ALB', name: '雅寶 (Albemarle 鋰礦)', englishName: 'Albemarle Corporation', category: '特種化學' },
  { symbol: 'ALGN', name: '愛齊科技 (隱適美)', englishName: 'Align Technology Inc.', category: '齒顎矯正' },
  { symbol: 'ALLE', name: '安朗傑 (Allegion)', englishName: 'Allegion plc', category: '安防五金' },
  { symbol: 'AMCR', name: '安姆科 (Amcor 包裝)', englishName: 'Amcor plc', category: '包裝材料' },
  { symbol: 'AME', name: '阿美特克 (AMETEK)', englishName: 'AMETEK Inc.', category: '精密儀器' },
  { symbol: 'AMP', name: '美盛金融 (Ameriprise)', englishName: 'Ameriprise Financial Inc.', category: '財富管理' },
  { symbol: 'AMT', name: '美國電塔 (American Tower)', englishName: 'American Tower Corporation', category: '電塔REIT' },
  { symbol: 'AON', name: '怡安保險 (Aon)', englishName: 'Aon plc Class A', category: '保險經紀' },
  { symbol: 'AOS', name: '史密斯熱水器 (A. O. Smith)', englishName: 'A. O. Smith Corporation', category: '熱水與淨水' },
  { symbol: 'APA', name: '阿帕契石油 (APA Corp)', englishName: 'APA Corporation', category: '石油開採' },
  { symbol: 'APTV', name: '安波福 (Aptiv 汽車電子)', englishName: 'Aptiv PLC', category: '車用電子' },
  { symbol: 'ARE', name: '亞歷山大房產 (Alexandria 生技機房)', englishName: 'Alexandria Real Estate Equities', category: '生醫地產REIT' },
  { symbol: 'ATO', name: '阿莫斯能源 (Atmos Energy)', englishName: 'Atmos Energy Corporation', category: '天然氣公用' },
  { symbol: 'AVY', name: '艾利丹尼森 (Avery Dennison)', englishName: 'Avery Dennison Corporation', category: '標籤包裝' },
  { symbol: 'AWK', name: '美國水務 (American Water Works)', englishName: 'American Water Works Company', category: '自來水公用' },
  { symbol: 'BALL', name: '波爾包裝 (Ball Corp 鋁罐金屬)', englishName: 'Ball Corporation', category: '金屬包裝' },
  { symbol: 'BAX', name: '百特醫療 (Baxter 透析洗腎)', englishName: 'Baxter International Inc.', category: '透析醫療' },
  { symbol: 'BBY', name: '百思買 (Best Buy 3C電器)', englishName: 'Best Buy Co. Inc.', category: '3C家電連鎖' },
  { symbol: 'BDX', name: '必帝醫療 (Becton Dickinson 注射針筒)', englishName: 'Becton Dickinson and Company', category: '醫療耗材' },
  { symbol: 'BEN', name: '富蘭克林坦伯頓 (Franklin Resources)', englishName: 'Franklin Resources Inc.', category: '共同基金資產管理' },
  { symbol: 'BF.B', name: '布朗霍文 (Brown-Forman 傑克丹尼威士忌)', englishName: 'Brown-Forman Corporation Class B', category: '烈酒釀造' },
  { symbol: 'BG', name: '邦吉 (Bunge 國際糧商四大ABCD之一)', englishName: 'Bunge Global SA', category: '農產品糧商' },
  { symbol: 'BXP', name: '波士頓地產 (BXP 頂級商辦REIT)', englishName: 'BXP Inc.', category: '商辦大樓REIT' },
  { symbol: 'CAG', name: '康尼格拉食品 (Conagra Brands)', englishName: 'Conagra Brands Inc.', category: '包裝食品' },
  { symbol: 'CAT', name: '開拓重工 (Caterpillar)', englishName: 'Caterpillar Inc.', category: '重型機具' },
  { symbol: 'CBRE', name: '世邦魏理仕 (CBRE 商用不動產)', englishName: 'CBRE Group Inc. Class A', category: '地產服務' },
  { symbol: 'CDW', name: 'CDW資訊科技通路', englishName: 'CDW Corporation', category: 'IT解決方案' },
  { symbol: 'CE', name: '塞拉尼斯 (Celanese 特種化學)', englishName: 'Celanese Corporation', category: '化學材料' },
  { symbol: 'CFG', name: '公民金融集團 (Citizens Financial)', englishName: 'Citizens Financial Group Inc.', category: '區域銀行' },
  { symbol: 'CHD', name: '雀馳 (Church & Dwight 小蘇打)', englishName: 'Church & Dwight Co. Inc.', category: '家用品' },
  { symbol: 'CHRW', name: '羅賓遜全球物流 (C.H. Robinson)', englishName: 'C.H. Robinson Worldwide Inc.', category: '貨運承攬' },
  { symbol: 'CLX', name: '高樂氏 (Clorox 漂白水與消毒)', englishName: 'The Clorox Company', category: '清潔消毒' },
  { symbol: 'CMA', name: '聯信銀行 (Comerica)', englishName: 'Comerica Incorporated', category: '商業銀行' },
  { symbol: 'CMS', name: 'CMS能源', englishName: 'CMS Energy Corporation', category: '電力公用' },
  { symbol: 'CNP', name: '中心點能源 (CenterPoint Energy)', englishName: 'CenterPoint Energy Inc.', category: '電力燃氣' },
  { symbol: 'COO', name: '庫博光學 (CooperCompanies 隱形眼鏡)', englishName: 'The Cooper Companies Inc.', category: '隱形眼鏡' },
  { symbol: 'CPB', name: '金寶湯 (Campbell Soup)', englishName: 'Campbell Soup Company', category: '濃湯食品' },
  { symbol: 'CPRT', name: '科帕特 (Copart 事故車拍賣龍頭)', englishName: 'Copart Inc.', category: '車輛在線拍賣' },
  { symbol: 'CPT', name: '康登地產 (Camden Property 公寓REIT)', englishName: 'Camden Property Trust', category: '住宅地產REIT' },
  { symbol: 'CRL', name: '查爾斯河實驗室 (Charles River 實驗動物)', englishName: 'Charles River Laboratories Intl', category: '生醫實驗CRO' },
  { symbol: 'CSGP', name: '科斯塔集團 (CoStar 房產大數據平台)', englishName: 'CoStar Group Inc.', category: '房地產數據' },
  { symbol: 'CTRA', name: '科特拉能源 (Coterra Energy)', englishName: 'Coterra Energy Inc.', category: '油氣開採' },
  { symbol: 'CTSH', name: '高知特資訊 (Cognizant IT外包)', englishName: 'Cognizant Technology Solutions', category: 'IT外包' },
  { symbol: 'CTVA', name: '科迪華 (Corteva 農業種子與農藥)', englishName: 'Corteva Inc.', category: '農化種子' },
  { symbol: 'CZR', name: '凱撒娛樂 (Caesars Entertainment 賭場連鎖)', englishName: 'Caesars Entertainment Inc.', category: '賭場博弈' },
  { symbol: 'DAY', name: '戴斯康 (Dayforce 雲端人資薪資)', englishName: 'Dayforce Inc.', category: '人資軟體' },
  { symbol: 'DHI', name: '霍頓房屋 (D.R. Horton 全美建商第一)', englishName: 'D.R. Horton Inc.', category: '住宅建商' },
  { symbol: 'DLB', name: '杜比實驗室 (Dolby 音效視覺)', englishName: 'Dolby Laboratories Inc.', category: '影音技術' },
  { symbol: 'DLR', name: '數位房產 (Digital Realty 資料中心REIT)', englishName: 'Digital Realty Trust Inc.', category: '資料中心REIT' },
  { symbol: 'DOV', name: '多佛 (Dover 多元工業)', englishName: 'Dover Corporation', category: '工業設備' },
  { symbol: 'DOW', name: '陶氏化學 (Dow 化學塑膠)', englishName: 'Dow Inc.', category: '大宗化學' },
  { symbol: 'DPZ', name: '達美樂比薩 (Domino\'s Pizza)', englishName: 'Domino\'s Pizza Inc.', category: '連鎖餐飲' },
  { symbol: 'DRI', name: '達頓餐飲 (Darden 橄欖園牛排連鎖)', englishName: 'Darden Restaurants Inc.', category: '休閒餐飲' },
  { symbol: 'DTE', name: 'DTE能源 (底特律電力網)', englishName: 'DTE Energy Company', category: '電力公用' },
  { symbol: 'ED', name: '聯合愛迪生 (Consolidated Edison 紐約電網)', englishName: 'Consolidated Edison Inc.', category: '電力公用' },
  { symbol: 'EFX', name: '艾可飛 (Equifax 徵信信用機構)', englishName: 'Equifax Inc.', category: '信用評估' },
  { symbol: 'EG', name: '珠峰再保險 (Everest Group)', englishName: 'Everest Group Ltd.', category: '再保險' },
  { symbol: 'EIX', name: '愛迪生國際 (Edison International 南加州電網)', englishName: 'Edison International', category: '電力公用' },
  { symbol: 'EMN', name: '伊士曼化工 (Eastman Chemical)', englishName: 'Eastman Chemical Company', category: '特種化工' },
  { symbol: 'ENPH', name: '安費諾微逆變器 (Enphase Energy 太陽能微逆變)', englishName: 'Enphase Energy Inc.', category: '太陽能逆變器' },
  { symbol: 'EOG', name: 'EOG資源 (頁岩油開採)', englishName: 'EOG Resources Inc.', category: '能源開採' },
  { symbol: 'EPAM', name: '億磐系統 (EPAM Systems 軟體工程)', englishName: 'EPAM Systems Inc.', category: '軟體研發' },
  { symbol: 'EQT', name: 'EQT能源 (全美最大天然氣生產商)', englishName: 'EQT Corporation', category: '天然氣開採' },
  { symbol: 'ERIE', name: '伊利保險 (Erie Indemnity)', englishName: 'Erie Indemnity Company Class A', category: '財產保險' },
  { symbol: 'ESS', name: '艾塞克斯產權 (Essex Property 西岸公寓REIT)', englishName: 'Essex Property Trust Inc.', category: '多戶公寓REIT' },
  { symbol: 'EVRG', name: '恆裕能源 (Evergy 堪薩斯電網)', englishName: 'Evergy Inc.', category: '電力公用' },
  { symbol: 'EW', name: '愛德華生命科學 (人工心臟瓣膜)', englishName: 'Edwards Lifesciences Corp.', category: '心臟醫療' },
  { symbol: 'EXC', name: '艾索倫電力 (Exelon 核電與輸電網)', englishName: 'Exelon Corporation', category: '電力公用' },
  { symbol: 'EXPD', name: '康捷國際物流 (Expeditors 貨代巨頭)', englishName: 'Expeditors International of Washington', category: '國際物流' },
  { symbol: 'EXR', name: '額外空間倉儲 (Extra Space Storage 迷你倉REIT)', englishName: 'Extra Space Storage Inc.', category: '自助倉儲REIT' },
  { symbol: 'F', name: '福特汽車 (Ford Motor)', englishName: 'Ford Motor Company', category: '傳統與電動車' },
  { symbol: 'FANG', name: '響尾蛇能源 (Diamondback Energy 二疊紀油氣)', englishName: 'Diamondback Energy Inc.', category: '頁岩油氣' },
  { symbol: 'FAST', name: '快扣 (Fastenal 工業螺絲耗材)', englishName: 'Fastenal Company', category: '工業供應鏈' },
  { symbol: 'FE', name: '第一能源 (FirstEnergy 俄亥俄電網)', englishName: 'FirstEnergy Corp.', category: '電力公用' },
  { symbol: 'FFIV', name: 'F5網路 (F5 負載均衡與資安)', englishName: 'F5 Inc.', category: '應用遞送' },
  { symbol: 'FIS', name: '富達國民資訊 (Fidelity National Info 金融核心系統)', englishName: 'Fidelity National Information Services', category: '銀行IT核心' },
  { symbol: 'FMC', name: '富美實 (FMC 農業殺蟲劑除草劑)', englishName: 'FMC Corporation', category: '農業化學' },
  { symbol: 'FOX', name: '福斯公司 B (Fox Corp 新聞體育)', englishName: 'Fox Corporation Class B', category: '廣播傳媒' },
  { symbol: 'FOXA', name: '福斯公司 A (Fox News 福斯新聞)', englishName: 'Fox Corporation Class A', category: '廣播傳媒' },
  { symbol: 'FRT', name: '聯邦不動產 (Federal Realty 頂級戶外商場REIT)', englishName: 'Federal Realty Investment Trust', category: '商場購物REIT' },
  { symbol: 'FSLR', name: '第一太陽能 (First Solar 薄膜太陽能板)', englishName: 'First Solar Inc.', category: '太陽能組件' },
  { symbol: 'GEN', name: '捷諾數位 (Gen Digital 諾頓防毒Norton)', englishName: 'Gen Digital Inc.', category: '消費防毒資安' },
  { symbol: 'GDDY', name: 'GoDaddy (網域註冊與主機)', englishName: 'GoDaddy Inc. Class A', category: '網域主機' },
  { symbol: 'GL', name: '全球人壽 (Globe Life 保險)', englishName: 'Globe Life Inc.', category: '人壽健康險' },
  { symbol: 'GM', name: '通用汽車 (General Motors 雪佛蘭/凱迪拉克)', englishName: 'General Motors Company', category: '汽車製造' },
  { symbol: 'GNRC', name: '捷諾克 (Generac 備用發電機龍頭)', englishName: 'Generac Holdings Inc.', category: '應急發電機' },
  { symbol: 'GPC', name: '正品汽車配件 (Genuine Parts NAPA連鎖)', englishName: 'Genuine Parts Company', category: '汽車維修零件' },
  { symbol: 'GRMN', name: '台灣國際航電 (Garmin 智慧手錶/航海GPS)', englishName: 'Garmin Ltd.', category: 'GPS穿戴裝置' },
  { symbol: 'HAL', name: '哈里伯頓 (Halliburton 壓裂工程)', englishName: 'Halliburton Company', category: '油田服務' },
  { symbol: 'HAS', name: '孩之寶 (Hasbro 變形金剛/萬智牌)', englishName: 'Hasbro Inc.', category: '玩具桌遊' },
  { symbol: 'HCA', name: 'HCA醫療 (全美最大私立連鎖醫院)', englishName: 'HCA Healthcare Inc.', category: '醫院運營' },
  { symbol: 'HES', name: '赫斯石油 (Hess 蓋亞那海上油田)', englishName: 'Hess Corporation', category: '深海油氣' },
  { symbol: 'HIG', name: '哈特福金融 (The Hartford 產物保險)', englishName: 'The Hartford Insurance Group', category: '商業財險' },
  { symbol: 'HII', name: '亨廷頓英格爾斯 (造船廠/核動力航母)', englishName: 'Huntington Ingalls Industries Inc.', category: '軍艦航母建造' },
  { symbol: 'HOLX', name: '豪洛捷 (Hologic 乳房攝影診斷)', englishName: 'Hologic Inc.', category: '女性健康檢測' },
  { symbol: 'HPQ', name: '惠普 (HP 印表機與筆電)', englishName: 'HP Inc.', category: '電腦印表機' },
  { symbol: 'HST', name: '萬豪地產信託 (Host Hotels & Resorts 奢華酒店REIT)', englishName: 'Host Hotels & Resorts Inc.', category: '酒店地產REIT' },
  { symbol: 'HUBB', name: '哈貝爾 (Hubbell 電力電氣開關)', englishName: 'Hubbell Incorporated', category: '電網電氣工程' },
  { symbol: 'HWM', name: '豪美特航太 (Howmet Aerospace 鈦合金鑄件)', englishName: 'Howmet Aerospace Inc.', category: '航太特種金屬' },
  { symbol: 'IEX', name: '埃迪克斯 (IDEX 特種泵浦與閥門)', englishName: 'IDEX Corporation', category: '流體計量設備' },
  { symbol: 'IFF', name: '國際香精香料 (IFF 食品香料)', englishName: 'International Flavors & Fragrances', category: '香精香料' },
  { symbol: 'INCY', name: '因賽特 (Incyte 骨髓纖維化藥物)', englishName: 'Incyte Corporation', category: '腫瘤生物製藥' },
  { symbol: 'INVH', name: '邀請住屋 (Invitation Homes 獨棟別墅出租REIT)', englishName: 'Invitation Homes Inc.', category: '獨棟住宅REIT' },
  { symbol: 'IP', name: '國際紙業 (International Paper 紙箱包裝)', englishName: 'International Paper Company', category: '瓦楞紙板' },
  { symbol: 'IPG', name: '埃培智集團 (Interpublic 廣告傳播)', englishName: 'The Interpublic Group of Companies', category: '廣告行銷' },
  { symbol: 'IR', name: '英格索蘭 (Ingersoll Rand 空壓機)', englishName: 'Ingersoll Rand Inc.', category: '空氣壓縮機' },
  { symbol: 'IRM', name: '鐵山 (Iron Mountain 機密文件與數據備份REIT)', englishName: 'Iron Mountain Incorporated', category: '檔案資料REIT' },
  { symbol: 'JBHT', name: '亨特貨運 (J.B. Hunt 鐵路公路多式聯運)', englishName: 'J.B. Hunt Transport Services Inc.', category: '貨櫃多式聯運' },
  { symbol: 'JBL', name: '捷普 (Jabil 電子代工製造EMS)', englishName: 'Jabil Inc.', category: '電子代工' },
  { symbol: 'JKHY', name: '傑克亨利 (Jack Henry 信用合作社銀行系統)', englishName: 'Jack Henry & Associates Inc.', category: '金融科技' },
  { symbol: 'KIM', name: '金科地產 (Kimco Realty 社區生鮮商場REIT)', englishName: 'Kimco Realty Corporation', category: '社區零售REIT' },
  { symbol: 'KMI', name: '金德摩根 (天然氣管線網絡)', englishName: 'Kinder Morgan Inc.', category: '油氣管道' },
  { symbol: 'KR', name: '克羅格 (Kroger 連鎖生鮮超市霸主)', englishName: 'The Kroger Co.', category: '大型超級市場' },
  { symbol: 'KVUE', name: '科赴 (Kenvue 李施德霖/露得清母公司)', englishName: 'Kenvue Inc.', category: '消費健康護理' },
  { symbol: 'L', name: '羅威斯集團 (Loews 控股/CNA保險)', englishName: 'Loews Corporation', category: '多元控股' },
  { symbol: 'LDOS', name: '理多斯 (Leidos 國防情報IT承包商)', englishName: 'Leidos Holdings Inc.', category: '軍事國防IT' },
  { symbol: 'LEN', name: '萊納房屋 (Lennar 全美第二大建商)', englishName: 'Lennar Corporation Class A', category: '住宅營造' },
  { symbol: 'LH', name: '萊博康 (Labcorp 全美醫學檢驗室)', englishName: 'Laboratory Corp. of America Holdings', category: '臨床醫檢' },
  { symbol: 'LHX', name: 'L3哈里斯 (L3Harris 軍用無線電通訊)', englishName: 'L3Harris Technologies Inc.', category: '國防電子通訊' },
  { symbol: 'LKQ', name: 'LKQ回收汽車零件', englishName: 'LKQ Corporation', category: '拆車二手零件' },
  { symbol: 'LNT', name: '阿蘭特能源 (Alliant Energy)', englishName: 'Alliant Energy Corporation', category: '電力公用' },
  { symbol: 'LULU', name: '露露樂蒙 (Lululemon 瑜伽運動服飾)', englishName: 'Lululemon Athletica Inc.', category: '運動瑜伽服' },
  { symbol: 'LYB', name: '利安德巴塞爾 (LyondellBasell 聚烯烴塑膠)', englishName: 'LyondellBasell Industries N.V.', category: '石化高分子' },
  { symbol: 'LYV', name: '理想國演藝 (Live Nation 演唱會門票Ticketmaster)', englishName: 'Live Nation Entertainment Inc.', category: '演唱會娛樂' },
  { symbol: 'MAA', name: '中大西洋公寓 (Mid-America Apartment REIT)', englishName: 'Mid-America Apartment Communities', category: '陽光帶公寓REIT' },
  { symbol: 'MAS', name: '美商美斯 (Masco 漢斯格雅衛浴蓮蓬頭)', englishName: 'Masco Corporation', category: '廚衛建材' },
  { symbol: 'MCO', name: '穆迪 (Moody\'s 信用評級與金融分析)', englishName: 'Moody\'s Corporation', category: '債信評級' },
  { symbol: 'MHK', name: '莫霍克工業 (Mohawk 地毯與磁磚製造)', englishName: 'Mohawk Industries Inc.', category: '地板地毯' },
  { symbol: 'MKC', name: '味好美 (McCormick 香辛料調味料)', englishName: 'McCormick & Company Inc.', category: '香辛料調味' },
  { symbol: 'MKTX', name: '市場軸線 (MarketAxess 債券電子交易平台)', englishName: 'MarketAxess Holdings Inc.', category: '債券交易Fintech' },
  { symbol: 'MLM', name: '馬丁瑪麗埃塔 (Martin Marietta 砂石骨料水泥)', englishName: 'Martin Marietta Materials Inc.', category: '砂石建材' },
  { symbol: 'MOH', name: '莫利納醫療 (Molina Healthcare 聯邦低收入醫保)', englishName: 'Molina Healthcare Inc.', category: 'Medicaid醫保' },
  { symbol: 'MOS', name: '美盛公司 (Mosaic 磷肥鉀肥生產)', englishName: 'The Mosaic Company', category: '農業化肥' },
  { symbol: 'MSI', name: '摩托羅拉系統 (Motorola Solutions 警用對講通訊)', englishName: 'Motorola Solutions Inc.', category: '公共安全通訊' },
  { symbol: 'MTD', name: '梅特勒-托利多 (Mettler-Toledo 精密天平秤量)', englishName: 'Mettler-Toledo International Inc.', category: '實驗室精密天平' },
  { symbol: 'NCLH', name: '挪威郵輪 (Norwegian Cruise Line)', englishName: 'Norwegian Cruise Line Holdings', category: '豪華郵輪' },
  { symbol: 'NDSN', name: '諾信 (Nordson 點膠機與精密塗布)', englishName: 'Nordson Corporation', category: '點膠封裝設備' },
  { symbol: 'NI', name: '源輝能源 (NiSource 印第安納電網)', englishName: 'NiSource Inc.', category: '電力燃氣' },
  { symbol: 'NVR', name: 'NVR房屋 (高品質預製建築建商)', englishName: 'NVR Inc.', category: '預製住宅建商' },
  { symbol: 'NWSA', name: '新聞集團 A (News Corp 華爾街日報母公司)', englishName: 'News Corporation Class A', category: '新聞財經出版' },
  { symbol: 'ODFL', name: '老自治領貨運 (Old Dominion 零擔物流零缺陷龍頭)', englishName: 'Old Dominion Freight Line Inc.', category: '零擔卡車物流' },
  { symbol: 'OMC', name: '宏盟集團 (Omnicom 全球四大廣告集團)', englishName: 'Omnicom Group Inc.', category: '廣告傳媒' },
  { symbol: 'ORLY', name: '歐萊禮汽車零件 (O\'Reilly 汽配連鎖店)', englishName: 'O\'Reilly Automotive Inc.', category: '汽車零組件零售' },
  { symbol: 'OXY', name: '西方石油 (Occidental Petroleum 巴菲特重押)', englishName: 'Occidental Petroleum Corporation', category: '頁岩油與碳捕集' },
  { symbol: 'PAYC', name: '沛康薪酬 (Paycom 雲端薪資與人資軟體)', englishName: 'Paycom Software Inc.', category: '薪資雲端' },
  { symbol: 'PAYX', name: '沛齊 (Paychex 中小企業薪酬外包)', englishName: 'Paychex Inc.', category: '薪資福利外包' },
  { symbol: 'PCAR', name: '帕卡卡車 (PACCAR 肯沃斯/彼得比爾特重卡)', englishName: 'PACCAR Inc.', category: '重型聯結車' },
  { symbol: 'PEG', name: '公用事業企業集團 (PSEG 新澤西電網)', englishName: 'Public Service Enterprise Group', category: '電力公用' },
  { symbol: 'PFE', name: '輝瑞製藥 (Pfizer 生物製藥與疫苗)', englishName: 'Pfizer Inc.', category: '跨國西藥廠' },
  { symbol: 'PFG', name: '信安金融 (Principal Financial 退休金管理)', englishName: 'Principal Financial Group Inc.', category: '401k退休金' },
  { symbol: 'PG', name: '寶僑 (Procter & Gamble 日用保養巨頭)', englishName: 'The Procter & Gamble Company', category: '家庭與個人護理' },
  { symbol: 'PKG', name: '美國包裝公司 (Packaging Corp 瓦楞紙盒)', englishName: 'Packaging Corporation of America', category: '包裝箱板紙' },
  { symbol: 'PLD', name: '普洛斯 (Prologis 全球最大物流地產REIT)', englishName: 'Prologis Inc.', category: '現代倉儲REIT' },
  { symbol: 'PNR', name: '濱特爾 (Pentair 游泳池水泵淨水處理)', englishName: 'Pentair plc', category: '水處理設備' },
  { symbol: 'PNW', name: '頂峰西能源 (Pinnacle West 亞利桑那電網)', englishName: 'Pinnacle West Capital Corporation', category: '電力公用' },
  { symbol: 'POOL', name: '泳池公司 (Pool Corp 游泳池設備耗材批發)', englishName: 'Pool Corporation', category: '泳池批發通路' },
  { symbol: 'PPG', name: 'PPG工業 (全球汽車與工業塗料)', englishName: 'PPG Industries Inc.', category: '油漆塗料' },
  { symbol: 'PPL', name: 'PPL電力 (賓州與肯塔基電網)', englishName: 'PPL Corporation', category: '電力公用' },
  { symbol: 'PRGO', name: '百利高 (Perrigo OTC非處方感冒藥)', englishName: 'Perrigo Company plc', category: 'OTC非處方藥' },
  { symbol: 'PSA', name: '大眾倉儲 (Public Storage 自助迷你倉)', englishName: 'Public Storage', category: '自助倉儲REIT' },
  { symbol: 'PSX', name: '菲利普斯66 (Phillips 66 煉化與石化原料)', englishName: 'Phillips 66', category: '石油煉化' },
  { symbol: 'PWR', name: '匡達服務 (Quanta Services AI電網與風電施工)', englishName: 'Quanta Services Inc.', category: '特高壓電網工程' },
  { symbol: 'PXD', name: '先鋒自然資源 (Pioneer Natural 頁岩油)', englishName: 'Pioneer Natural Resources Co.', category: '能源探勘' },
  { symbol: 'RCL', name: '皇家加勒比郵輪 (Royal Caribbean 海洋綠洲號)', englishName: 'Royal Caribbean Cruises Ltd.', category: '豪華海島郵輪' },
  { symbol: 'REG', name: '攝政地產 (Regency Centers 頂級超市賣場REIT)', englishName: 'Regency Centers Corporation', category: '購物中心REIT' },
  { symbol: 'RF', name: '地區金融 (Regions Financial 美國南部銀行)', englishName: 'Regions Financial Corporation', category: '商業銀行' },
  { symbol: 'RHI', name: '羅伯特半人馬 (Robert Half 人才獵頭顧問)', englishName: 'Robert Half Inc.', category: '人力獵頭派遣' },
  { symbol: 'RJF', name: '雷蒙詹姆斯金融 (Raymond James 獨立財富管理)', englishName: 'Raymond James Financial Inc.', category: '證券財富管理' },
  { symbol: 'RL', name: '雷夫羅倫 (Ralph Lauren 馬球POLO衫名牌)', englishName: 'Ralph Lauren Corporation', category: '高級時尚精品' },
  { symbol: 'RMD', name: '瑞思邁 (ResMed 睡眠呼吸暫停治療器)', englishName: 'ResMed Inc.', category: '睡眠呼吸醫療' },
  { symbol: 'ROK', name: '洛克威爾自動化 (Rockwell 工廠自動化控制器)', englishName: 'Rockwell Automation Inc.', category: '工業自動化PLC' },
  { symbol: 'ROL', name: '羅林斯 (Rollins 奧爾金Orkin專業白蟻害蟲防治)', englishName: 'Rollins Inc.', category: '病媒害蟲防治' },
  { symbol: 'ROP', name: '羅珀科技 (Roper Technologies 垂直利基軟體)', englishName: 'Roper Technologies Inc.', category: '利基企業軟體' },
  { symbol: 'ROST', name: '羅斯百貨 (Ross Stores 尋寶折扣服飾)', englishName: 'Ross Stores Inc.', category: '折扣名牌服飾' },
  { symbol: 'RSG', name: '共和廢品 (Republic Services 垃圾環保收運)', englishName: 'Republic Services Inc.', category: '廢棄物清理' },
  { symbol: 'RVTY', name: '瑞萊特 (Revvity 癌症篩檢與生科試劑)', englishName: 'Revvity Inc.', category: '新生兒篩檢儀' },
  { symbol: 'SBAC', name: 'SBA通訊 (SBA Communications 基地台鐵塔REIT)', englishName: 'SBA Communications Corp.', category: '5G通訊鐵塔REIT' },
  { symbol: 'SBUX', name: '星巴克 (Starbucks 連鎖義式精品咖啡)', englishName: 'Starbucks Corporation', category: '連鎖咖啡連鎖' },
  { symbol: 'SCHW', name: '嘉信理財 (Charles Schwab 零手續費券商龍頭)', englishName: 'The Charles Schwab Corporation', category: '零售證券券商' },
  { symbol: 'SHW', name: '宣偉漆 (Sherwin-Williams 建築汽車專用塗料)', englishName: 'The Sherwin-Williams Company', category: '塗料油漆王牌' },
  { symbol: 'SJM', name: '斯味可 (The J.M. Smucker 花生醬與果醬)', englishName: 'The J.M. Smucker Company', category: '果醬寵物食品' },
  { symbol: 'SLB', name: '斯倫貝謝 (SLB 全球最大油田技術服務)', englishName: 'Schlumberger Limited', category: '鑽井油田服務' },
  { symbol: 'SNA', name: '實耐寶 (Snap-on 頂級終身保固修車手工具)', englishName: 'Snap-on Incorporated', category: '高階修車工具' },
  { symbol: 'SNPS', name: '新思科技 (Synopsys 晶片EDA設計工具軟體)', englishName: 'Synopsys Inc.', category: '晶片設計EDA' },
  { symbol: 'SO', name: '南方電力 (The Southern Company 美國核電電網)', englishName: 'The Southern Company', category: '電力公用事業' },
  { symbol: 'SPG', name: '西蒙地產 (Simon Property 全美最大Outlet購物中心REIT)', englishName: 'Simon Property Group Inc.', category: '名品商場REIT' },
  { symbol: 'SPGI', name: '標普全球 (S&P Global 標普500指數與債信評級)', englishName: 'S&P Global Inc.', category: '金融大數據評級' },
  { symbol: 'SRE', name: '森普拉能源 (Sempra 南加州天然氣與LNG出口)', englishName: 'Sempra', category: '天然氣電網LNG' },
  { symbol: 'STE', name: '思泰瑞 (STERIS 手術室滅菌與消毒設備)', englishName: 'STERIS plc', category: '醫院滅菌設備' },
  { symbol: 'STLD', name: '鋼動力 (Steel Dynamics 現代化電弧爐短流程煉鋼)', englishName: 'Steel Dynamics Inc.', category: '低碳循環鋼鐵' },
  { symbol: 'STT', name: '道富銀行 (State Street 全球託管銀行與SPY發行商)', englishName: 'State Street Corporation', category: '資產託管與ETF' },
  { symbol: 'STX', name: '希捷科技 (Seagate 硬碟儲存製造)', englishName: 'Seagate Technology Holdings plc', category: '大容量資料硬碟' },
  { symbol: 'STZ', name: '星座品牌 (Constellation Brands 可樂娜啤酒Corona)', englishName: 'Constellation Brands Inc.', category: '進口啤酒葡萄酒' },
  { symbol: 'SWK', name: '史丹利百得 (Stanley Black & Decker 電動工具)', englishName: 'Stanley Black & Decker Inc.', category: '五金電動工具' },
  { symbol: 'SWKS', name: '思佳訊 (Skyworks 射頻前端5G晶片)', englishName: 'Skyworks Solutions Inc.', category: '手機射頻晶片' },
  { symbol: 'SYF', name: '同步金融 (Synchrony 聯名信用卡發卡商)', englishName: 'Synchrony Financial', category: '零售聯名信用卡' },
  { symbol: 'SYK', name: '史賽克 (Stryker 人工關節與手術設備)', englishName: 'Stryker Corporation', category: '骨科醫療器材' },
  { symbol: 'SYY', name: '西斯科 (Sysco 餐廳飯店生鮮食材供應鏈巨無霸)', englishName: 'Sysco Corporation', category: '餐飲食材供應鏈' },
  { symbol: 'TAP', name: '摩森康勝 (Molson Coors 庫爾斯淡啤酒)', englishName: 'Molson Coors Beverage Company', category: '啤酒釀造' },
  { symbol: 'TDG', name: '全美達 (TransDigm 專利航太零件超高毛利霸主)', englishName: 'TransDigm Group Incorporated', category: '航太專利零件' },
  { symbol: 'TDY', name: '特利丹科技 (Teledyne 紅外線夜視與深海儀器)', englishName: 'Teledyne Technologies Inc.', category: '軍工感測光電' },
  { symbol: 'TECH', name: '生物技術公司 (Bio-Techne 蛋白質生技試劑)', englishName: 'Bio-Techne Corp.', category: '細胞生物試劑' },
  { symbol: 'TEL', name: '泰科電子 (TE Connectivity 車用連接器與感測器)', englishName: 'TE Connectivity Ltd.', category: '高壓連接器' },
  { symbol: 'TER', name: '泰瑞達 (Teradyne 晶片半導體自動化測試機台)', englishName: 'Teradyne Inc.', category: '晶片測試設備' },
  { symbol: 'TFX', name: '泰利福 (Teleflex 血管介入急救導管)', englishName: 'Teleflex Incorporated', category: '重症急救醫療' },
  { symbol: 'TGT', name: '目標百貨 (Target 美國大型連鎖精品百貨量販)', englishName: 'Target Corporation', category: '大型零售百貨' },
  { symbol: 'TJX', name: 'TJX公司 (T.J. Maxx / Marshalls 名牌折扣服飾連鎖)', englishName: 'The TJX Companies Inc.', category: '折扣精品名牌' },
  { symbol: 'TMO', name: '賽默飛世爾 (Thermo Fisher 科學儀器與耗材巨擘)', englishName: 'Thermo Fisher Scientific Inc.', category: '生醫科學儀器' },
  { symbol: 'TPR', name: '掛毯集團 (Tapestry Coach / Kate Spade 精品皮件)', englishName: 'Tapestry Inc.', category: '輕奢精品名牌' },
  { symbol: 'TRGP', name: '塔爾加資源 (Targa Resources 天然氣液體NGL收集)', englishName: 'Targa Resources Corp.', category: '天然氣管網' },
  { symbol: 'TRMB', name: '天寶導航 (Trimble 智慧農業與工程測繪GPS)', englishName: 'Trimble Inc.', category: '工程測繪衛星' },
  { symbol: 'TROW', name: '普信集團 (T. Rowe Price 主動型投資管理)', englishName: 'T. Rowe Price Group Inc.', category: '基金資產管理' },
  { symbol: 'TRV', name: '旅行家保險 (The Travelers Companies 商業產險)', englishName: 'The Travelers Companies Inc.', category: '商業綜合保險' },
  { symbol: 'TSCO', name: '拖拉機供應 (Tractor Supply 鄉村戶外生活雜貨)', englishName: 'Tractor Supply Company', category: '農村生活用品' },
  { symbol: 'TSN', name: '泰森食品 (Tyson Foods 全美最大雞肉牛肉肉品加工)', englishName: 'Tyson Foods Inc. Class A', category: '肉類生鮮加工' },
  { symbol: 'TT', name: '特靈科技 (Trane 智慧節能冷氣暖通HVAC)', englishName: 'Trane Technologies plc', category: '商業冷凍空調' },
  { symbol: 'TTWO', name: 'Take-Two互動 (俠盜獵車手GTA / 2K遊戲發行商)', englishName: 'Take-Two Interactive Software', category: '熱門主機遊戲' },
  { symbol: 'TXN', name: '德州儀器 (TI 類比晶片與嵌入式微處理器霸主)', englishName: 'Texas Instruments Incorporated', category: '類比晶片龍頭' },
  { symbol: 'TYL', name: '泰勒科技 (Tyler Technologies 市政府公部門專用ERP)', englishName: 'Tyler Technologies Inc.', category: '公部門政府軟體' },
  { symbol: 'UDR', name: '聯合自治區房產 (UDR 高級多戶公寓出租REIT)', englishName: 'UDR Inc.', category: '精華區公寓REIT' },
  { symbol: 'UHS', name: '環球健康服務 (Universal Health 急診與精神心理醫院)', englishName: 'Universal Health Services Inc.', category: '行為健康醫院' },
  { symbol: 'ULTA', name: 'Ulta美容 (Ulta Beauty 一站式美妝沙龍連鎖)', englishName: 'Ulta Beauty Inc.', category: '化妝品沙龍' },
  { symbol: 'UNH', name: '聯合健康 (UnitedHealth 全球最大醫療保險與Optum醫療)', englishName: 'UnitedHealth Group Incorporated', category: '健康保險醫療' },
  { symbol: 'UNP', name: '聯合太平洋 (Union Pacific 橫貫美國西部一級鐵路)', englishName: 'Union Pacific Corporation', category: '一級重載鐵路' },
  { symbol: 'UPS', name: '優比速 (UPS 每日處理全球數千萬包裹物流)', englishName: 'United Parcel Service Inc.', category: '全球物流包裹' },
  { symbol: 'URI', name: '聯合租賃 (United Rentals 建築重機具與發電機租賃)', englishName: 'United Rentals Inc.', category: '工程設備租賃' },
  { symbol: 'USB', name: '美國合眾銀行 (U.S. Bancorp 歷史悠久優質區域銀行)', englishName: 'U.S. Bancorp', category: '全美前五大銀行' },
  { symbol: 'V', name: 'Visa (全球最大電子支付清算網絡系統)', englishName: 'Visa Inc.', category: '全球支付清算' },
  { symbol: 'VICI', name: 'VICI地產 (持有拉斯維加斯百樂宮與凱撒宮博弈地產REIT)', englishName: 'VICI Properties Inc.', category: '博弈賭場REIT' },
  { symbol: 'VLO', name: '瓦萊羅能源 (Valero 全美頂級獨立石油煉製商)', englishName: 'Valero Energy Corporation', category: '石油煉化' },
  { symbol: 'VLTO', name: '韋爾拓 (Veralto 水質分析與產品包裝檢測)', englishName: 'Veralto Corporation', category: '水質淨化檢測' },
  { symbol: 'VMC', name: '伏爾甘材料 (Vulcan Materials 碎石骨料瀝青水泥製造)', englishName: 'Vulcan Materials Company', category: '基礎設施砂石' },
  { symbol: 'VRSK', name: '維里斯克 (Verisk Analytics 保險精算大數據分析)', englishName: 'Verisk Analytics Inc.', category: '保險大數據風控' },
  { symbol: 'VRSN', name: '威 sign (VeriSign .com與.net全球頂級網域獨家管理者)', englishName: 'VeriSign Inc.', category: '根網域獨占營運' },
  { symbol: 'VRTX', name: '福泰製藥 (Vertex 囊腫性纖維化與基因編輯新藥CRISPR)', englishName: 'Vertex Pharmaceuticals Inc.', category: '罕見病基因治療' },
  { symbol: 'VST', name: '維斯達能源 (Vistra AI資料中心全天候清潔發電商)', englishName: 'Vistra Corp.', category: '獨立電力運營' },
  { symbol: 'VTR', name: '溫塔斯 (Ventas 養老照護中心與醫療大樓REIT)', englishName: 'Ventas Inc.', category: '醫療養老REIT' },
  { symbol: 'WAB', name: '西屋制動 (Wabtec 火車機車頭與煞車鐵路系統)', englishName: 'Westinghouse Air Brake Technologies', category: '鐵路機車製造' },
  { symbol: 'WAT', name: '沃特世 (Waters 液相層析儀與質譜儀實驗設備)', englishName: 'Waters Corporation', category: '化學分析儀器' },
  { symbol: 'WBA', name: '沃爾格林聯合博姿 (Walgreens 連鎖社區藥局連鎖)', englishName: 'Walgreens Boots Alliance Inc.', category: '連鎖藥妝超市' },
  { symbol: 'WBD', name: '華納兄弟探索 (Warner Bros. Discovery HBO / 華納電影院)', englishName: 'Warner Bros. Discovery Inc.', category: '影視傳媒與串流' },
  { symbol: 'WDC', name: '威騰電子 (Western Digital 快閃記憶體與硬碟)', englishName: 'Western Digital Corporation', category: '儲存快閃記憶體' },
  { symbol: 'WEC', name: 'WEC能源 (威斯康辛電力與天然氣)', englishName: 'WEC Energy Group Inc.', category: '電力燃氣公用' },
  { symbol: 'WELL', name: '衛健地產 (Welltower 全球最大銀髮高齡住宅社區REIT)', englishName: 'Welltower Inc.', category: '銀髮照護REIT' },
  { symbol: 'WFC', name: '富國銀行 (Wells Fargo 全美最大房貸零售銀行)', englishName: 'Wells Fargo & Company', category: '多元金融銀行' },
  { symbol: 'WM', name: '廢物管理 (Waste Management 全美第一大垃圾清理回收)', englishName: 'Waste Management Inc.', category: '環保垃圾清理' },
  { symbol: 'WMB', name: '威廉斯 (Williams 橫跨全美天然氣長途集輸管道)', englishName: 'The Williams Companies Inc.', category: '天然氣管線網絡' },
  { symbol: 'WMT', name: '沃爾瑪 (Walmart 全球營收最大跨國零售實體巨無霸)', englishName: 'Walmart Inc.', category: '跨國量販超市' },
  { symbol: 'WRB', name: '伯克利保險 (W. R. Berkley 特種商業責任保險)', englishName: 'W. R. Berkley Corporation', category: '特種超額保險' },
  { symbol: 'WST', name: '西氏醫藥包裝 (West Pharmaceutical 疫苗注射橡膠塞蓋)', englishName: 'West Pharmaceutical Services Inc.', category: '針劑醫療包裝' },
  { symbol: 'WTW', name: '韋萊韜悅 (Willis Towers Watson 企業風險人資顧問)', englishName: 'Willis Towers Watson Public Limited', category: '企業風險諮詢' },
  { symbol: 'WY', name: '惠好 (Weyerhaeuser 北美最大林業與木材REIT)', englishName: 'Weyerhaeuser Company', category: '林業原木REIT' },
  { symbol: 'WYNN', name: '永利渡假村 (Wynn Resorts 頂級奢華賭場酒店渡假村)', englishName: 'Wynn Resorts Limited', category: '奢華度假賭城' },
  { symbol: 'XEL', name: '埃克塞爾能源 (Xcel Energy 綠能轉型風力發電公用)', englishName: 'Xcel Energy Inc.', category: '風力發電公用' },
  { symbol: 'XOM', name: '埃克森美孚 (ExxonMobil 全球最大一體化跨國石油巨擘)', englishName: 'Exxon Mobil Corporation', category: '石油天然氣龍頭' },
  { symbol: 'XYL', name: '賽萊默 (Xylem 全球智慧水處理水泵防洪解決方案)', englishName: 'Xylem Inc.', category: '智慧水科技設備' },
  { symbol: 'YUM', name: '百勝餐飲 (Yum! Brands 肯德基KFC / 必勝客Pizza Hut)', englishName: 'Yum! Brands Inc.', category: '全球速食連鎖' },
  { symbol: 'ZBH', name: '捷邁邦美 (Zimmer Biomet 人工膝關節與髖關節植入物)', englishName: 'Zimmer Biomet Holdings Inc.', category: '骨科植入關節' },
  { symbol: 'ZBRA', name: '斑馬技術 (Zebra Technologies 條碼掃描槍與RFID手持機)', englishName: 'Zebra Technologies Corporation', category: '條碼物流終端' },
  { symbol: 'ZTS', name: '碩騰 (Zoetis 輝瑞獨立之全球第一大動物藥品疫苗)', englishName: 'Zoetis Inc.', category: '伴侶寵物製藥' },
];

console.log('Additional US stocks ready:', additionalUS.length);
